decision_tree_1:
  - id: 1
    variable: ""
    condition: ""
    left_id: -1
    right_id: -1
    action: ""
  - id: 2
    variable: ""
    condition: ""
    left_id: -1
    right_id: -1
    action: ""
  - id: 3
    variable: ""
    condition: ""
    left_id: -1
    right_id: -1
    action: ""
  - id: 4
    variable: ""
    condition: ""
    left_id: -1
    right_id: -1
    action: ""